export const english = {
  "description": "Connect agents to MCP servers and HTTP APIs through one governed gateway. Control tool access, approve writes and return only the fields your agents need.",
  "ogTitle": "Rillgate — Give agents access. Keep control.",
  "ogDescription": "One gateway for your agents and tools. Reviewed connections, scoped access, human approvals and focused responses.",
  "pageTitle": "Rillgate — MCP Gateway for AI agents",
  "skip": "Skip to content",
  "homeLabel": "Rillgate home",
  "navLabel": "Main navigation",
  "how": "How it works",
  "response": "Response control",
  "docs": "Docs",
  "workspace": "Open workspace",
  "heroEyebrow": "THE ACCESS LAYER FOR YOUR AGENTS",
  "heroFirst": "Give agents",
  "heroSecond": "access.",
  "heroLast": "Keep control",
  "heroIntro": "Your agents. Your tools. One governed gateway.",
  "heroDescription": "Connect MCP servers and HTTP APIs with clear permissions and focused responses.",
  "github": "Explore on GitHub",
  "heroNote": "Built for teams. Cloud workspace · Invitation-only access.",
  "mapLabel": "Agent clients connect to Rillgate, which checks access, approvals and response policies before connecting to remote MCP servers or HTTP APIs. The operation ledger records the outcome.",
  "mapHeading": "ONE CONNECTION. CLEAR BOUNDARIES.",
  "pi": "Pi agent",
  "runtime": "Task runtime",
  "client": "MCP client",
  "stack": "Your agent stack",
  "controlPoint": "THE CONTROL POINT",
  "access": "✓ Scoped access",
  "approvals": "✓ Write approvals",
  "policy": "✓ Response policy",
  "servers": "MCP servers",
  "services": "Existing services",
  "ledger": "Every governed operation leaves a record.",
  "principle": "DESIGNED AROUND THE CALL",
  "connectPrinciple": "Connect deliberately.",
  "actPrinciple": "Act with permission.",
  "returnPrinciple": "Return what matters.",
  "flowEyebrow": "01 / A CLEAR PATH TO EVERY TOOL",
  "flowFirst": "From connection",
  "flowLast": "to confidence.",
  "flowIntro": "Bring your services into a shared catalog.",
  "flowDescription": "Keep the decisions that matter in your team’s hands.",
  "connectTitle": "Connect & review",
  "connectDescription": "Discover remote MCP tools or register an HTTP API. Review contracts and publish the versions you trust.",
  "connectLink": "Explore connections",
  "governTitle": "Grant & govern",
  "governDescription": "Scope each client’s access. Require an independent reviewer to approve writes before the gateway dispatches them.",
  "governLink": "Explore client access",
  "executeTitle": "Execute & inspect",
  "executeDescription": "Apply response policies and follow the operation to its recorded outcome. Keep uncertain writes visible for review.",
  "executeLink": "See what’s implemented",
  "responseEyebrow": "02 / LESS NOISE. MORE SIGNAL.",
  "responseFirst": "The right fields.",
  "responseLast": "A clearer context.",
  "responseDescription": "A tool can return more than an agent needs. Choose which structured fields pass through, preserve pagination, and set a final response size limit.",
  "responseLink": "Read the response contract",
  "responseNoteFirst": "Policies shape the stored and returned result.",
  "responseNoteLast": "Upstream data transfer stays unchanged.",
  "illustration": "ILLUSTRATIVE SAMPLE",
  "sampleViewLabel": "Sample response view",
  "upstream": "Upstream response",
  "projected": "After field selection",
  "sampleCodeLabel": "Sample response JSON",
  "sampleTitle": "Connect your first server",
  "projectedNote": "2 selected fields · Pagination retained",
  "operateEyebrow": "03 / BUILT FOR THE DAY AFTER SETUP",
  "operateFirst": "Your tools evolve.",
  "operateLast": "Stay in the loop.",
  "operateIntro": "A shared workspace for the people",
  "operateDescription": "responsible for agent access.",
  "catalogLabel": "Illustration of a catalog change awaiting human review",
  "catalog": "CATALOG REVIEW",
  "review": "Review required",
  "schema": "Illustrative schema change",
  "optional": "optional",
  "required": "required",
  "unpublished": "Changes stay unpublished until reviewed.",
  "driftTitle": "Catch changes before you publish",
  "driftDescription": "Schedule catalog checks. Compare schema drift, new tools and missing tools against your registered versions.",
  "auditTitle": "Know who did what",
  "auditDescription": "Inspect client permissions, approval decisions and operation history from one workspace.",
  "uncertaintyTitle": "Keep uncertainty explicit",
  "uncertaintyDescription": "Ambiguous writes remain UNKNOWN. Add review evidence without silently retrying a business action.",
  "buildEyebrow": "YOUR INFRASTRUCTURE. YOUR BOUNDARIES.",
  "buildFirst": "A gateway you",
  "buildLast": "can look inside.",
  "buildIntro": "Explore the Go backend, React workspace and Pi runner.",
  "buildDescription": "Follow the implementation, deployment guides and roadmap on GitHub.",
  "repository": "Explore the repository",
  "deploy": "Read the deployment guide",
  "buildStatus": "Actively developed · Current scope documented",
  "tagline": "Give agents access. Keep control.",
  "footerLabel": "Footer navigation",
  "status": "Project status",
  "footerWorkspace": "Workspace",
  "heroPeriod": ".",
  "languageLabel": "Website language",
  "sampleContent": "Register an upstream, discover its tools, review the contract, and publish.",
  "upstreamNote": "6 upstream fields · Before field selection"
} as const;

export type WebsiteCopy = Record<keyof typeof english, string>;
export const chinese: WebsiteCopy = {
  "description": "通过统一网关连接智能体、MCP 服务和 HTTP API，管理工具权限、审批写入操作，只返回智能体所需的字段",
  "ogTitle": "Rillgate — 让智能体连接工具，让调用可控",
  "ogDescription": "为智能体和工具提供统一入口：接入审查、权限控制、人工审批与响应裁剪",
  "pageTitle": "Rillgate — 面向 AI 智能体的 MCP 网关",
  "skip": "跳转到正文",
  "homeLabel": "Rillgate 首页",
  "navLabel": "主导航",
  "how": "工作方式",
  "response": "响应裁剪",
  "docs": "文档",
  "workspace": "进入工作台",
  "heroEyebrow": "为智能体连接工具，定义边界",
  "heroFirst": "让智能体",
  "heroSecond": "连接工具",
  "heroLast": "让调用可控",
  "heroIntro": "你的智能体，你的工具，一个可管控的网关",
  "heroDescription": "统一接入 MCP 服务与 HTTP API，明确权限，精简响应",
  "github": "在 GitHub 上探索",
  "heroNote": "为团队打造 · 云端工作台 · 邀请制访问",
  "mapLabel": "智能体客户端通过 Rillgate 访问远程 MCP 服务或 HTTP API，网关检查权限、审批与响应策略，并记录每次操作的结果",
  "mapHeading": "统一入口，清晰边界",
  "pi": "Pi 智能体",
  "runtime": "任务执行",
  "client": "MCP 客户端",
  "stack": "你的智能体应用",
  "controlPoint": "统一管控",
  "access": "✓ 权限控制",
  "approvals": "✓ 写入审批",
  "policy": "✓ 响应策略",
  "servers": "MCP 服务",
  "services": "现有业务服务",
  "ledger": "每次受控调用，都有记录可查",
  "principle": "围绕每次调用设计",
  "connectPrinciple": "接入经过审查",
  "actPrinciple": "执行遵循权限",
  "returnPrinciple": "返回所需信息",
  "flowEyebrow": "01 / 从接入到执行",
  "flowFirst": "连接工具，",
  "flowLast": "让调用有据可循",
  "flowIntro": "将业务服务纳入共享工具目录",
  "flowDescription": "把关键决策留在团队手中",
  "connectTitle": "接入与审查",
  "connectDescription": "发现远程 MCP 工具，或注册 HTTP API，审查接口定义，发布经过确认的版本",
  "connectLink": "了解服务接入",
  "governTitle": "授权与管控",
  "governDescription": "为每个客户端限定访问范围，写入操作先由独立审批人确认，再由网关执行",
  "governLink": "了解客户端授权",
  "executeTitle": "执行与追踪",
  "executeDescription": "应用响应策略，追踪每次调用及其结果，保留结果不确定的写入操作，交由人工核查",
  "executeLink": "查看已实现能力",
  "responseEyebrow": "02 / 精简响应，保留重点",
  "responseFirst": "留下必要字段，",
  "responseLast": "让上下文更清晰",
  "responseDescription": "工具返回的内容可能超过智能体所需，选择保留的结构化字段，延续分页信息，并限制最终响应大小",
  "responseLink": "阅读响应规范",
  "responseNoteFirst": "策略作用于存储和返回的结果",
  "responseNoteLast": "上游传输的数据量保持不变",
  "illustration": "示例数据",
  "sampleViewLabel": "示例响应视图",
  "upstream": "上游原始响应",
  "projected": "字段裁剪后",
  "sampleCodeLabel": "示例响应 JSON",
  "sampleTitle": "接入第一个服务",
  "projectedNote": "保留 2 个字段 · 保留分页信息",
  "operateEyebrow": "03 / 接入之后，持续管控",
  "operateFirst": "工具持续变化，",
  "operateLast": "每次变更心中有数",
  "operateIntro": "为负责智能体访问的团队，",
  "operateDescription": "提供共享的管理工作台",
  "catalogLabel": "工具目录变更等待人工审查的示意图",
  "catalog": "目录审查",
  "review": "等待审查",
  "schema": "接口定义变更示例",
  "optional": "可选",
  "required": "必填",
  "unpublished": "变更经审查后才会发布",
  "driftTitle": "发布前，发现变更",
  "driftDescription": "定时检查工具目录，对比已注册版本，识别接口定义变化、新增和缺失的工具",
  "auditTitle": "谁做了什么，清晰可查",
  "auditDescription": "在同一工作台中查看客户端权限、审批记录与操作历史",
  "uncertaintyTitle": "让不确定结果保持可见",
  "uncertaintyDescription": "无法确认结果的写入保持 UNKNOWN 状态，补充人工核查证据，避免自动重试业务操作",
  "buildEyebrow": "你的基础设施，你来定义边界",
  "buildFirst": "看得见实现，",
  "buildLast": "管得住调用",
  "buildIntro": "了解 Go 后端、React 工作台与 Pi 任务执行器",
  "buildDescription": "在 GitHub 查看实现、部署指南与开发路线",
  "repository": "查看代码仓库",
  "deploy": "阅读部署指南",
  "buildStatus": "持续开发中 · 已公开当前实现范围",
  "tagline": "连接工具，掌控调用",
  "footerLabel": "页脚导航",
  "status": "项目进度",
  "footerWorkspace": "工作台",
  "heroPeriod": "",
  "languageLabel": "网站语言",
  "sampleContent": "注册上游服务，发现工具，审查接口定义，再发布工具",
  "upstreamNote": "上游 6 个字段 · 裁剪前"
};
