export const english = {
  "description": "Connect enterprise tools to AI agents through one MCP gateway. Discover authorized tools, approve business actions and trace every operation to its outcome.",
  "ogTitle": "Rillgate — Give agents access. Keep control.",
  "ogDescription": "One gateway for enterprise tools and agents. On-demand discovery, scoped access, independent write approval and durable operation records.",
  "pageTitle": "Rillgate — MCP Gateway for AI agents",
  "skip": "Skip to content",
  "homeLabel": "Rillgate home",
  "navLabel": "Main navigation",
  "how": "How it works",
  "docs": "Docs",
  "workspace": "Open workspace",
  "heroEyebrow": "THE ACCESS LAYER FOR YOUR AGENTS",
  "heroFirst": "Give agents",
  "heroSecond": "access.",
  "heroLast": "Keep control",
  "heroIntro": "Your business tools. Your rules for every action.",
  "heroDescription": "Connect MCP servers and HTTP APIs. Control who can act, approve writes and follow every outcome.",
  "github": "Explore on GitHub",
  "heroNote": "Built for teams. Cloud workspace · Invitation-only access.",
  "mapLabel": "Agent clients reach MCP servers and HTTP APIs through Rillgate. The gateway checks client permissions, requires independent approval for writes and records operation outcomes.",
  "mapHeading": "ONE CONNECTION. CLEAR BOUNDARIES.",
  "pi": "Pi agent",
  "runtime": "Task runtime",
  "client": "MCP client",
  "stack": "Your agent stack",
  "controlPoint": "THE CONTROL POINT",
  "access": "✓ Scoped access",
  "approvals": "✓ Write approvals",
  "servers": "MCP servers",
  "services": "Existing services",
  "ledger": "Every governed operation leaves a record.",
  "principle": "DESIGNED AROUND THE CALL",
  "connectPrinciple": "Connect deliberately.",
  "actPrinciple": "Act with permission.",
  "returnPrinciple": "Keep a record.",
  "flowEyebrow": "01 / A CLEAR PATH TO EVERY TOOL",
  "flowFirst": "Your existing tools.",
  "flowLast": "One governed entry.",
  "flowIntro": "Bring MCP servers and HTTP APIs into a shared catalog.",
  "flowDescription": "Let each agent discover the tools it is allowed to use.",
  "connectTitle": "Connect & review",
  "connectDescription": "Discover remote MCP tools or register an HTTP API. Review contracts and publish the versions you trust.",
  "connectLink": "Explore connections",
  "governTitle": "Discover on demand",
  "governDescription": "Search authorized tool summaries, then load the schema of the selected tool when it is needed.",
  "governLink": "Read the discovery contract",
  "executeTitle": "Authorize each client",
  "executeDescription": "Grant access to specific servers and tools. Check current permissions again before dispatching an operation.",
  "executeLink": "Explore client access",
  "operateEyebrow": "03 / KEEP YOUR TOOL CATALOG UNDER CONTROL",
  "operateFirst": "Your tools evolve.",
  "operateLast": "Stay in the loop.",
  "operateIntro": "Review changes, inspect operations",
  "operateDescription": "and tune tool responses from one workspace.",
  "catalogLabel": "Illustration of a catalog change awaiting human review",
  "catalog": "CATALOG REVIEW",
  "review": "Review required",
  "schema": "Illustrative schema change",
  "optional": "optional",
  "required": "required",
  "unpublished": "Changes stay unpublished until reviewed.",
  "driftTitle": "Catch changes before you publish",
  "driftDescription": "Schedule catalog checks. Compare schema drift, new tools and missing tools against your registered versions.",
  "auditTitle": "Know who did what",
  "auditDescription": "Inspect client permissions, approval decisions and operation history from one workspace.",
  "buildEyebrow": "YOUR INFRASTRUCTURE. YOUR BOUNDARIES.",
  "buildFirst": "A gateway you",
  "buildLast": "can look inside.",
  "buildIntro": "Explore the Go backend, React workspace and Pi runner.",
  "buildDescription": "Follow the implementation, deployment guides and roadmap on GitHub.",
  "repository": "Explore the repository",
  "deploy": "Read the deployment guide",
  "buildStatus": "Actively developed · Current scope documented",
  "tagline": "Give agents access. Keep control.",
  "footerLabel": "Footer navigation",
  "status": "Project status",
  "footerWorkspace": "Workspace",
  "heroPeriod": ".",
  "languageLabel": "Website language",
  "history": "✓ Operation records",
  "executionNav": "Execution",
  "executionEyebrow": "02 / FROM INTENT TO A RECORDED OUTCOME",
  "executionFirst": "Approve the action.",
  "executionLast": "Trace the outcome.",
  "executionDescription": "Follow a write request from tool discovery to independent approval and a recorded result. If the response is lost, keep the uncertainty visible.",
  "executionLink": "Explore the execution model",
  "executionNoteFirst": "Each operation retains its tool version and inputs.",
  "executionNoteLast": "Idempotency keys identify repeated requests.",
  "operationTitle": "Create a support ticket",
  "operationIllustration": "WORKFLOW ILLUSTRATION",
  "scenarioLabel": "Choose an example outcome",
  "scenarioSuccess": "Completed",
  "scenarioUnknown": "Response lost",
  "discoverStep": "Discover a tool",
  "discoverDetail": "Find a published tool within the client’s grants.",
  "authorizeStep": "Check access",
  "authorizeDetail": "Check client access and validate inputs.",
  "approveStep": "Approve the write",
  "approveDetail": "Another reviewer approves this write.",
  "dispatchStep": "Dispatch the call",
  "dispatchDetail": "Recheck permissions and record dispatch.",
  "outcomeStep": "Record the outcome",
  "successTitle": "Result confirmed",
  "successDetail": "The tool returned a confirmed result. Inspect the approval and execution record together.",
  "unknownTitle": "Result needs verification",
  "unknownDetail": "The request was sent, but its outcome could not be confirmed. The gateway does not automatically replay the write.",
  "unknownEvidence": "A reviewer can append evidence; the original UNKNOWN state is retained.",
  "operationCaption": "Illustrative flow · No business service is called",
  "responseFeatureTitle": "Return only what is needed",
  "responseFeatureDescription": "Select structured fields, retain pagination and bound the stored and returned response. Upstream transfer stays unchanged.",
  "responseFeatureLink": "Read the response contract"
} as const;

export type WebsiteCopy = Record<keyof typeof english, string>;
export const chinese: WebsiteCopy = {
  "description": "通过统一 MCP 网关把企业工具接给智能体，按权限发现工具、审批业务操作，并追踪每次调用的结果",
  "ogTitle": "Rillgate — 让智能体连接工具，让调用可控",
  "ogDescription": "为企业工具和智能体提供统一入口，支持按需发现、客户端授权、独立写入审批与持久化操作记录",
  "pageTitle": "Rillgate — 面向 AI 智能体的 MCP 网关",
  "skip": "跳转到正文",
  "homeLabel": "Rillgate 首页",
  "navLabel": "主导航",
  "how": "工作方式",
  "docs": "文档",
  "workspace": "进入工作台",
  "heroEyebrow": "为智能体连接工具，定义边界",
  "heroFirst": "让智能体",
  "heroSecond": "连接工具",
  "heroLast": "让调用可控",
  "heroIntro": "把企业现有工具接给 Agent",
  "heroDescription": "统一接入 MCP 与 HTTP API，让业务操作有授权、有审批、有记录",
  "github": "在 GitHub 上探索",
  "heroNote": "为团队打造 · 云端工作台 · 邀请制访问",
  "mapLabel": "智能体通过 Rillgate 访问 MCP 服务和 HTTP API，网关检查客户端权限，要求写入操作由独立审批人确认，并记录操作结果",
  "mapHeading": "统一入口，清晰边界",
  "pi": "Pi 智能体",
  "runtime": "任务执行",
  "client": "MCP 客户端",
  "stack": "你的智能体应用",
  "controlPoint": "统一管控",
  "access": "✓ 权限控制",
  "approvals": "✓ 写入审批",
  "servers": "MCP 服务",
  "services": "现有业务服务",
  "ledger": "每次受控调用，都有记录可查",
  "principle": "围绕每次调用设计",
  "connectPrinciple": "接入经过审查",
  "actPrinciple": "执行遵循权限",
  "returnPrinciple": "每次操作留痕",
  "flowEyebrow": "01 / 从接入到执行",
  "flowFirst": "企业现有工具，",
  "flowLast": "统一接给智能体",
  "flowIntro": "将 MCP 服务与 HTTP API 纳入共享目录",
  "flowDescription": "让智能体按需发现自己有权使用的工具",
  "connectTitle": "接入与审查",
  "connectDescription": "发现远程 MCP 工具，或注册 HTTP API，审查接口定义，发布经过确认的版本",
  "connectLink": "了解服务接入",
  "governTitle": "按需发现",
  "governDescription": "先搜索有权使用的工具摘要，选定工具后再获取完整参数定义",
  "governLink": "了解工具发现",
  "executeTitle": "按客户端授权",
  "executeDescription": "为客户端限定可访问的服务和工具，执行操作前再次核验当前权限",
  "executeLink": "了解客户端授权",
  "operateEyebrow": "03 / 接入之后，持续治理",
  "operateFirst": "工具持续变化，",
  "operateLast": "每次变更心中有数",
  "operateIntro": "在同一工作台审查工具变更、查看操作记录",
  "operateDescription": "并配置工具返回的内容",
  "catalogLabel": "工具目录变更等待人工审查的示意图",
  "catalog": "目录审查",
  "review": "等待审查",
  "schema": "接口定义变更示例",
  "optional": "可选",
  "required": "必填",
  "unpublished": "变更经审查后才会发布",
  "driftTitle": "发布前，发现变更",
  "driftDescription": "定时检查工具目录，对比已注册版本，识别接口定义变化、新增和缺失的工具",
  "auditTitle": "谁做了什么，清晰可查",
  "auditDescription": "在同一工作台中查看客户端权限、审批记录与操作历史",
  "buildEyebrow": "你的基础设施，你来定义边界",
  "buildFirst": "看得见实现，",
  "buildLast": "管得住调用",
  "buildIntro": "了解 Go 后端、React 工作台与 Pi 任务执行器",
  "buildDescription": "在 GitHub 查看实现、部署指南与开发路线",
  "repository": "查看代码仓库",
  "deploy": "阅读部署指南",
  "buildStatus": "持续开发中 · 已公开当前实现范围",
  "tagline": "连接工具，掌控调用",
  "footerLabel": "页脚导航",
  "status": "项目进度",
  "footerWorkspace": "工作台",
  "heroPeriod": "",
  "languageLabel": "网站语言",
  "history": "✓ 操作记录",
  "executionNav": "受控执行",
  "executionEyebrow": "02 / 从工具发现到结果核查",
  "executionFirst": "写入先审批，",
  "executionLast": "结果可追踪",
  "executionDescription": "以创建工单为例，串起工具发现、权限核验、独立审批和执行记录，响应中断时也能明确下一步如何处理",
  "executionLink": "了解执行机制",
  "executionNoteFirst": "每次操作保留工具版本与请求参数",
  "executionNoteLast": "通过幂等键识别同一请求",
  "operationTitle": "一次工单创建请求",
  "operationIllustration": "流程示意",
  "scenarioLabel": "选择示例结果",
  "scenarioSuccess": "正常完成",
  "scenarioUnknown": "响应中断",
  "discoverStep": "发现工具",
  "discoverDetail": "查找当前客户端有权使用的已发布工具",
  "authorizeStep": "校验权限",
  "authorizeDetail": "检查客户端授权与请求参数",
  "approveStep": "独立审批",
  "approveDetail": "由另一位审批人确认本次写入操作",
  "dispatchStep": "执行调用",
  "dispatchDetail": "再次核验授权，并记录操作派发状态",
  "outcomeStep": "记录结果",
  "successTitle": "结果已确认",
  "successDetail": "工具已返回确认结果，可查看对应的审批与执行记录",
  "unknownTitle": "结果待核查",
  "unknownDetail": "请求已发出，但执行结果尚未确认，网关不会自动重放这次写入",
  "unknownEvidence": "由人工核查并追加证据，原始 UNKNOWN 状态保持不变",
  "operationCaption": "流程示意 · 不会调用业务服务",
  "responseFeatureTitle": "只返回需要的内容",
  "responseFeatureDescription": "选择保留的结构化字段，延续分页信息，限制存储与返回的响应大小，上游传输量保持不变",
  "responseFeatureLink": "了解响应裁剪"
};
